require("../node_modules/bootstrap/dist/css/bootstrap.min.css");
require("../resources/styles/css/reset.css");
require("../node_modules/animate.css/animate.min.css");
require('../node_modules/angular-ui-bootstrap/dist/ui-bootstrap-csp.css');
require("../node_modules/gumga-login/dist/gumga-login.min.css");
require("../resources/styles/css/gumga/gumga.min.css");
require("../gumga-layout/gumga-layout.min.css");
require("../node_modules/gumga-report-ng/dist/stimulsoft/css/stimulsoft.designer.office2013.darkgrayteal.css");
require("../node_modules/gumga-report-ng/dist/stimulsoft/css/stimulsoft.viewer.office2013.darkgrayteal.css");
